// <auto-generated />
using System;
using AdherenceService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdherenceService.Migrations
{
    [DbContext(typeof(AdherenceDbContext))]
    partial class AdherenceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdherenceService.Models.AdherenceRecord", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MedicationId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ScheduledDoseTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualDoseTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("AlertTriggered")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDoseTaken")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("UserId", "MedicationId", "ScheduledDoseTime");

                    b.ToTable("AdherenceRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
