@APIGateway_HostAddress = http://localhost:5290

### Get the Gateway Status (Custom Controller Endpoint)
GET {{APIGateway_HostAddress}}/Gateway/status
Accept: application/json

###

### (Optional) Test a Routed Endpoint via Ocelot
### For example, if you have a downstream auth service route defined in ocelot.json:
GET {{APIGateway_HostAddress}}/auth/test
Accept: application/json

###
